[package]
name = "tokenizers"
version = "0.1.0"
edition = "2021"

[lib]
name = "mtokenizers"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
encoding = "0.2.33"
pyo3 = {version = "0.19.0", features = ["extension-module"]}
